--------------------------------------------------------
--  파일이 생성됨 - 토요일-7월-11-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARDE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARDE" 
   (	"NUM" NUMBER(20,0), 
	"WRITER" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"SUBJECT" VARCHAR2(75 BYTE), 
	"PASSWD" VARCHAR2(12 BYTE), 
	"REG_DATE" TIMESTAMP (6), 
	"READCOUNT" NUMBER DEFAULT 0, 
	"REF" NUMBER(20,0), 
	"RE_STEP" NUMBER(10,0), 
	"RE_LEVEL" NUMBER(10,0), 
	"CONTENT" LONG, 
	"IP" VARCHAR2(20 BYTE), 
	"FILENAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008227
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C008227" ON "SCOTT"."BOARDE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARDE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARDE" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("IP" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("RE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("RE_STEP" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARDE" MODIFY ("NUM" NOT NULL ENABLE);
